name: Mirror to Codeberg

on:
  push:
    branches: [ main, master ]

jobs:
  codeberg_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          CB_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          # Pushing directly to your specific NickAtLinux Codeberg repository
          git push --prune --force https://NickAtLinux:${CB_TOKEN}@codeberg.org/NickAtLinux/Narnia-Server-Client-Modpack-mirror.git refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
